### PR TITLE
Made fancy settings a submodule

### PR DESCRIPTION
**Pull request by M4T1A5**
Added fancy settings as a submodule for being more git

### CODE REVIEW

**Comment by M4T1A5** [comment]
A very short tutorial for updating a submodule in this context.
git submodule init && git submodule update
cd fancy-settings
git checkout master
git pull
cd ..
Now everything is ready to be committed and pushed with the latest version of Fancy Settings

**Comment by Kerrick** [comment]
The problem is, I've changed the functionality of fancy-settings by adding in my own support for textareas. Using the current version just wouldn't work.

Also, the fancy-settings manifest in which I set up the options lives in the fancy-settings directory. Using fancy-settings as a submodule uses the default manifest file, so I can't specify my own settings.

While I like the idea, how would these problems be solved?

**Comment by M4T1A5** [comment]
http://book.git-scm.com/5_submodules.html info on how to keep changes in a submodule but if you think it's too hard then maybe this should not be used

**Comment by Kerrick** [comment]
I read that page four times trying to understand, and I just couldn't wrap my head around it. Of course, I haven't been mentally with it for days, I've been ill. I'm going to close this for now, but I'll revisit the topic of submodules in the future. :)

**Pull request closed without merging**
